# Generated by Django 5.1.6 on 2025-03-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('profile_picture', models.URLField(blank=True, max_length=500, null=True, verbose_name='Foto')),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data Nasc.')),
                ('categories', models.JSONField(blank=True, default=list, null=True, verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
