# Generated by Django 5.1.6 on 2025-04-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('investimento_minimo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Investimento Mínimo')),
                ('porcentagem_cedida', models.CharField(blank=True, max_length=255, null=True, verbose_name='Porcentagem Cedida')),
                ('categorias', models.JSONField(blank=True, default=list, null=True, verbose_name='Categorias')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='ideias/', verbose_name='Imagem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_innovations', to='api.user')),
                ('partners', models.ManyToManyField(blank=True, related_name='partnered_innovations', to='api.user')),
            ],
            options={
                'verbose_name': 'Ideia',
                'verbose_name_plural': 'Ideias',
            },
        ),
    ]
