# Generated by Django 5.1.6 on 2025-04-27 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_innovation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovation',
            name='imagem',
        ),
        migrations.AddField(
            model_name='innovation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='innovation',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.CreateModel(
            name='InnovationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='Innovation/', verbose_name='Foto')),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.innovation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_innovationsimages', to='api.user')),
            ],
            options={
                'verbose_name': 'Imagem da Ideia',
                'verbose_name_plural': 'Imagens das Ideias',
            },
        ),
    ]
