# Generated by Django 5.1.6 on 2025-05-10 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_negotiationroom_negotiationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationmessage',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='api.user'),
            preserve_default=False,
        ),
    ]
