# Generated by Django 5.1.6 on 2025-06-01 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_proposalinnovation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('no_plan', 'No plan'), ('esmerald', 'Esmerald'), ('sapphire', 'Sapphire'), ('ruby', 'Ruby')], default='no_plan', max_length=20, verbose_name='Plano'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('plan', models.CharField(choices=[('no_plan', 'No plan'), ('esmerald', 'Esmerald'), ('sapphire', 'Sapphire'), ('ruby', 'Ruby')], max_length=20, verbose_name='Plano')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('succeeded', 'Sucesso'), ('failed', 'Falhou'), ('cancelled', 'Cancelado'), ('requires_action', 'Requer Ação')], default='pending', max_length=20, verbose_name='Status')),
                ('stripe_payment_intent_id', models.CharField(max_length=100, unique=True, verbose_name='Stripe Payment Intent ID')),
                ('stripe_client_secret', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe Client Secret')),
                ('payment_method_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Method ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='api.user')),
            ],
            options={
                'verbose_name': 'Transação de Pagamento',
                'verbose_name_plural': 'Transações de Pagamento',
                'ordering': ['-created'],
            },
        ),
    ]
