# Generated by Django 5.1.6 on 2025-06-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_balance_credittransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('cancelled', 'Cancelada'), ('completed', 'Concluída')], default='active', max_length=50, verbose_name='Status'),
        ),
    ]
