# Generated by Django 5.1.6 on 2025-06-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_innovation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('cancelled', 'Cancelada')], default='active', max_length=50, verbose_name='Status'),
        ),
    ]
