# Generated by Django 5.1.6 on 2025-06-08 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_proposalinnovation_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('signer_name', models.CharField(max_length=255, verbose_name='Nome do Signatário')),
                ('signer_email', models.EmailField(max_length=254, verbose_name='Email do Signatário')),
                ('document_type', models.CharField(max_length=50, verbose_name='Tipo do Documento')),
                ('document_number', models.CharField(max_length=50, verbose_name='Número do Documento')),
                ('user_role', models.CharField(max_length=50, verbose_name='Papel do Usuário')),
                ('signed_at', models.DateTimeField(verbose_name='Assinado em')),
                ('contract_hash', models.TextField(verbose_name='Hash do Contrato')),
                ('signed_pdf_file', models.FileField(blank=True, help_text='Arquivo PDF do contrato assinado', null=True, upload_to='signed_contracts/', verbose_name='PDF Assinado')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp de Segurança')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('platform', models.CharField(max_length=255, verbose_name='Plataforma')),
                ('language', models.CharField(max_length=10, verbose_name='Idioma')),
                ('screen_resolution', models.CharField(max_length=50, verbose_name='Resolução da Tela')),
                ('timezone', models.CharField(max_length=100, verbose_name='Fuso Horário')),
                ('contract_title', models.CharField(max_length=500, verbose_name='Título do Contrato')),
                ('contract_subtitle', models.CharField(blank=True, max_length=500, verbose_name='Subtítulo do Contrato')),
                ('contract_description', models.TextField(verbose_name='Descrição do Contrato')),
                ('investment_amount', models.CharField(max_length=255, verbose_name='Valor do Investimento')),
                ('equity_percentage', models.CharField(max_length=255, verbose_name='Porcentagem de Participação')),
                ('innovation_name', models.CharField(max_length=255, verbose_name='Nome da Inovação')),
                ('status', models.CharField(choices=[('signed', 'Assinado'), ('cancelled', 'Cancelado')], default='signed', max_length=50, verbose_name='Status')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='api.proposalinnovation')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_signatures', to='api.user')),
            ],
            options={
                'verbose_name': 'Assinatura de Contrato',
                'verbose_name_plural': 'Assinaturas de Contratos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProposalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Investimento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('succeeded', 'Sucesso'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_payments', to='api.user')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api.proposalinnovation')),
            ],
            options={
                'verbose_name': 'Pagamento de Proposta',
                'verbose_name_plural': 'Pagamentos de Propostas',
                'ordering': ['-created'],
            },
        ),
    ]
