# Generated by Django 5.1.6 on 2025-06-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_proposalinnovation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan',
            field=models.CharField(choices=[('no_plan', 'Gratuito'), ('esmerald', 'Esmerald'), ('sapphire', 'Sapphire'), ('ruby', 'Ruby')], max_length=20, verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('no_plan', 'Gratuito'), ('esmerald', 'Esmerald'), ('sapphire', 'Sapphire'), ('ruby', 'Ruby')], default='no_plan', max_length=20, verbose_name='Plano'),
        ),
    ]
