
services:
  db:
    image: postgres:13.5
    container_name: PI4SEM
    environment:
      - POSTGRES_DB=PI4SEM
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: